.github/workflows/deploy-hub.yaml

runs deployment steps automatically on every change to deployment files, so changes can be deployed via PR without any local operations

deploy hub from github actions

---

jupyterhub/config/daskhub.yaml
jupyterhub/deploy.py
jupyterhub/gfts-hub/Chart.lock
jupyterhub/gfts-hub/Chart.yaml
jupyterhub/gfts-hub/values.yaml
jupyterhub/images/user/Dockerfile
jupyterhub/images/user/requirements.txt
terraform/main.tf

image is now a minimally modified pangeo-notebook
dask-gateway is also installed with low resource limits for now

deploy dask-gateway, pangeo base image

---

.github/workflows/pre-commit.yaml

so folks can see linter output

run pre-commit on ci

---

jupyterhub/images/user/Dockerfile
jupyterhub/images/user/conda-requirements.txt
jupyterhub/images/user/requirements.txt

install xarray-healpy in user image

---

.github/workflows/test-image.yaml
jupyterhub/deploy.py

to test image updates, like #17

build images on pull request

---

jupyterhub/gfts-hub/values.yaml

enable local iframes

---

README.md
docs/_config.yml
docs/conf.py
docs/intro.md
docs/references.bib

The DESP name is no longer in use

Update DESP name to DestinE Platform

---

.binder/environment.yml

My understanding is that this is now a requirement for this notebook
https://destination-earth.github.io/DestinE_ESA_GFTS/pannel_plot_s3.html

Add moving pandas to env

---

gfts-track-reconstruction/jupyterhub/gfts-hub/values.yaml
gfts-track-reconstruction/jupyterhub/tofu/main.tf

current quota only supports one of these
@tinaok

add large 480GB node pool

---

docs/GFTS_Use_Case_Description.md
docs/_toc.yml

Based on the deliverable GFTS D5.2 Use Case Descriptor

add use case description

---

gfts-track-reconstruction/jupyterhub/images/user/Dockerfile

to resolve issues related to libGL.so.1 when installing some packages for interactive visualisation

add openGL library

---

CITATION.cff
README.md
codemeta.json

to increase the FAIRness of the GFTS software

Follow FAIR4RS guidelines

---

gfts-track-reconstruction/jupyterhub/tofu/main.tf

increases available parallelism

increase large node limit to match current quota

---

gfts-track-reconstruction/jupyterhub/gfts-hub/values.yaml

some tags seem to require slightly more than 120

add 160GB profile to kbatch

---

webapp/deploy/helm/Chart.lock
webapp/deploy/helm/Chart.yaml
webapp/deploy/helm/templates/ingress.yaml
webapp/deploy/helm/values.yaml

https://github.com/destination-earth/DestinE_ESA_GFTS/issues/101

Add certifcate for webapp domain.

---

scripts/simplify.py

Adds the time series data from the tracker measurements to the most probable track.
Keeps average and std for each day. The tracking data is much more detailed at the order of minutes.
@tinaok do you think this is a good way to summarize the measurements? I could also add min/max to this if better.
Closes #119

Time and average

---

scripts/groups.py

Simply adding two xarray datasets drops dimensions that do not match. So we were loosing quarters throughout the loop. This fixes the calculations.

Fix grouping operation

---

scripts/groups.py

Threshold probabilities at 1e-7

Add snipped to convert zarr to parquet

---

docs/papermill_launcher2.ipynb

Hi,
I added a new notebook that illustrates how to process tag batches with `pangeo-fish` and `kbatch_papermill`.
Since I think that it can be improved later, I haven't included it in the documentation (as the other notebook about `kbatch_papermill`).

New notebook for launching jobs with `pangeo-fish`

---

gfts-track-reconstruction/jupyterhub/gfts-hub/values.yaml

@minrk From my notes, this is what’s needed to add a new user. Let me know if I missed anything. Thanks!

Add Etienne as kbatch user

---

gfts-track-reconstruction/jupyterhub/gfts-hub/Chart.lock
gfts-track-reconstruction/jupyterhub/gfts-hub/values.yaml

allows selection of image. Currently a stock pangeo image and the last image known to work before s3 problems, so we can test if that is indeed the culprit

add image selection in profiles

---

gfts-track-reconstruction/jupyterhub/gfts-hub/values.yaml

avoids s3 errors when putting files due to https://github.com/boto/boto3/issues/4392

set AWS_REQUEST_CHECKSUM_CALCULATION=WHEN_REQUIRED

---

gfts-track-reconstruction/jupyterhub/images/user/Dockerfile

2025-04-03
gets updated datashader (>=0.17) which should be compatible with dask 2025
cc @QuentinMaz

update pangeo base image

---

.github/workflows/deploy.yml

We need to deliver a zipped version to DestinE for integration with their docs.

Store zipped docs in a gh action artifact

---

LICENSE
docs/_config.yml

Should have done this from the start!
Will wait for approval from both @annefou and @tinaok before merging.

Better copyright now includes Simula and Ifremer
